from tkinter import *
window=Tk()
window.title("Welcome")
window.minsize(width=200,height=400)
window.maxsize(width=400,height=200)
f1=Frame()
f1.pack()
f2=Frame()
f2.pack(side=BOTTOM)
l1=Label(f1,text="I am at the top")
l1.pack()
l2=Label(f2,text="I am at the bottom")
l2.pack()
window.mainloop()